# Generated by Django 5.2.8 on 2025-11-27 10:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('type_utilisateur', models.CharField(choices=[('ETUDIANT', 'Étudiant'), ('PROFESSEUR', 'Professeur'), ('ADMINISTRATEUR', 'Administrateur')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=150)),
                ('volume_horaire', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'db_table': 'cours',
            },
        ),
        migrations.CreateModel(
            name='EtudiantGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Étudiant-Groupe',
                'verbose_name_plural': 'Étudiants-Groupes',
                'db_table': 'etudiant_groupe',
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('niveau', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
                'db_table': 'filiere',
            },
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Groupe',
                'verbose_name_plural': 'Groupes',
                'db_table': 'groupe',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notification',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaine', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('annee', models.IntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Planning',
                'verbose_name_plural': 'Plannings',
                'db_table': 'planning',
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT_JUSTIFIE', 'Absent Justifié'), ('ABSENT_NON_JUSTIFIE', 'Absent Non Justifié')], max_length=30)),
                ('justification', models.TextField(blank=True, null=True)),
                ('fichier_justificatif', models.BinaryField(blank=True, null=True)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'db_table': 'presence',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('annee_scolaire', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'db_table': 'promotion',
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('salle', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Séance',
                'verbose_name_plural': 'Séances',
                'db_table': 'seance',
            },
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='admin_profile', serialize=False, to='Home.utilisateur')),
            ],
            options={
                'verbose_name': 'Administrateur',
                'verbose_name_plural': 'Administrateurs',
                'db_table': 'administrateur',
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='etudiant_profile', serialize=False, to='Home.utilisateur')),
                ('code_etudiant', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
                'db_table': 'etudiant',
            },
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='prof_profile', serialize=False, to='Home.utilisateur')),
                ('specialite', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Professeur',
                'verbose_name_plural': 'Professeurs',
                'db_table': 'professeur',
            },
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['email'], name='utilisateur_email_5ac882_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['type_utilisateur'], name='utilisateur_type_ut_2f7d9b_idx'),
        ),
        migrations.AddField(
            model_name='etudiantgroupe',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.groupe'),
        ),
        migrations.AddField(
            model_name='notification',
            name='presence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Home.presence'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='Home.filiere'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes', to='Home.promotion'),
        ),
        migrations.AddField(
            model_name='seance',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='Home.cours'),
        ),
        migrations.AddField(
            model_name='seance',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='Home.groupe'),
        ),
        migrations.AddField(
            model_name='seance',
            name='planning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='Home.planning'),
        ),
        migrations.AddField(
            model_name='presence',
            name='seance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='Home.seance'),
        ),
        migrations.AddField(
            model_name='planning',
            name='administrateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plannings', to='Home.administrateur'),
        ),
        migrations.AddField(
            model_name='presence',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='Home.etudiant'),
        ),
        migrations.AddField(
            model_name='notification',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Home.etudiant'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='etudiants',
            field=models.ManyToManyField(related_name='groupes', through='Home.EtudiantGroupe', to='Home.etudiant'),
        ),
        migrations.AddField(
            model_name='etudiantgroupe',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.etudiant'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants', to='Home.promotion'),
        ),
        migrations.AddField(
            model_name='cours',
            name='professeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='Home.professeur'),
        ),
        migrations.AddIndex(
            model_name='seance',
            index=models.Index(fields=['date'], name='seance_date_eaa911_idx'),
        ),
        migrations.AddIndex(
            model_name='seance',
            index=models.Index(fields=['cours'], name='seance_cours_i_c2b223_idx'),
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['etudiant'], name='presence_etudian_e0e039_idx'),
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['seance'], name='presence_seance__dcf2ba_idx'),
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['statut'], name='presence_statut_b93aed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together={('etudiant', 'seance')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['etudiant'], name='notificatio_etudian_8cf913_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='etudiantgroupe',
            unique_together={('etudiant', 'groupe')},
        ),
        migrations.AddIndex(
            model_name='etudiant',
            index=models.Index(fields=['code_etudiant'], name='etudiant_code_et_a20276_idx'),
        ),
    ]
