# Generated by Django 5.2.8 on 2026-01-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('ABSENCE', "Notification d'absence"), ('JUSTIFICATION_ACCEPTEE', 'Justification acceptée'), ('JUSTIFICATION_REFUSEE', 'Justification refusée'), ('AUTRE', 'Autre')], db_column='type_notification', default='ABSENCE', max_length=30),
        ),
        migrations.AddField(
            model_name='presence',
            name='notification_absence_cree',
            field=models.BooleanField(db_column='notification_absence_cree', default=False),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type_notification'], name='notificatio_type_no_99f075_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['lu'], name='notificatio_lu_f290e4_idx'),
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['notification_absence_cree'], name='presence_notific_07ab8d_idx'),
        ),
    ]
