# Generated by Django 5.2.8 on 2025-12-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_presence_statut_justification'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['statut_justification'], name='presence_statut__cf6a74_idx'),
        ),
    ]
