# Generated by Django 5.2.8 on 2026-01-03 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_notification_type_notification_and_more'),
    ]

    operations = [
    ]
