# Generated by Django 5.2.8 on 2026-01-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_add_notification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='dernier_seuil_alerte',
            field=models.IntegerField(db_column='dernier_seuil_alerte', default=0),
        ),
    ]
