# Generated by Django 5.2.8 on 2026-01-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_etudiant_dernier_seuil_alerte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('ABSENCE', "Notification d'absence"), ('JUSTIFICATION_ACCEPTEE', 'Justification acceptée'), ('JUSTIFICATION_REFUSEE', 'Justification refusée'), ('ALERTE_SEUIL', "Alerte seuil d'absences"), ('ALERTE_SERIEUSE', 'Alerte sérieuse'), ('ALERTE_CRITIQUE', 'Alerte critique'), ('AUTRE', 'Autre')], db_column='type_notification', default='ABSENCE', max_length=30),
        ),
        migrations.AddIndex(
            model_name='etudiant',
            index=models.Index(fields=['dernier_seuil_alerte'], name='etudiant_dernier_9596b5_idx'),
        ),
    ]
