# Generated by Django 5.2.8 on 2026-01-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_notification_type_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('ABSENCE', "Notification d'absence"), ('JUSTIFICATION_ACCEPTEE', 'Justification acceptée'), ('JUSTIFICATION_REFUSEE', 'Justification refusée'), ('ALERTE_ABSENCES', "Alerte nombre d'absences"), ('AUTRE', 'Autre')], db_column='type_notification', default='ABSENCE', max_length=30),
        ),
    ]
