<<<<<<< HEAD
# Generated by Django 5.2.8 on 2025-11-30 15:13
=======
# Generated by Django 5.2.8 on 2025-11-28 23:47
>>>>>>> 2e85289e870c9bb608dfa9d388270d523a561fa0

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professeurs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Professeur',
        ),
    ]
