# Generated by Django 5.2.8 on 2025-12-11 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Absenceflow', '__first__'),
        ('professeurs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professeur',
            name='matricule',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='user',
        ),
        migrations.AddField(
            model_name='professeur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='professeur',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Absenceflow.groupe'),
        ),
        migrations.AddField(
            model_name='professeur',
            name='groupes',
            field=models.ManyToManyField(blank=True, related_name='professeurs', to='Absenceflow.groupe'),
        ),
        migrations.AddField(
            model_name='professeur',
            name='matiere',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='professeur',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='professeur',
            name='planning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Absenceflow.planning'),
        ),
        migrations.AddField(
            model_name='professeur',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
